version: "v2.24.6"

services:
  db:
    image: postgres:16.2
    env_file:
      - .env
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createsuperuser --username=${DJANGO_SUPERUSER_USERNAME} --email=${DJANGO_SUPERUSER_EMAIL} --noinput &&
             exec gunicorn --bind 0.0.0.0:$PORT kp.wsgi:application"

