version: "v2.24.6"

services:
  db:
    image: postgres:16.2
    env_file:
      - .env
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

