# Generated by Django 5.0.2 on 2024-06-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kp_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Art1PageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("font", models.CharField(max_length=100)),
                ("font_color", models.CharField(max_length=7)),
                ("edu_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="UserCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
