# Generated by Django 5.0.2 on 2024-08-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kp_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("font", models.CharField(max_length=100)),
                ("font_color", models.CharField(max_length=100)),
                ("font_style", models.CharField(max_length=100)),
                ("blog_title", models.CharField(max_length=100)),
                ("blog_text", models.TextField()),
                ("edu_facebook", models.URLField()),
                ("edu_instagram", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image1_filename", models.CharField(max_length=255)),
                (
                    "image2_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image3_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image4_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
