# Generated by Django 5.0.2 on 2024-07-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kp_app", "0002_art1pagesettings_usercredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="Art2PageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("font", models.CharField(max_length=100)),
                ("font_color", models.CharField(max_length=100)),
                ("edu_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="HomePage1Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HomePage2Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homepage2_text", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Test",
        ),
        migrations.AlterField(
            model_name="art1pagesettings",
            name="font_color",
            field=models.CharField(max_length=100),
        ),
    ]
