# Generated by Django 5.0.2 on 2024-09-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kp_app", "0003_artcategory_artwork_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtCategoryPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("font", models.CharField(max_length=100)),
                ("font_color", models.CharField(max_length=100)),
                ("edu_email", models.EmailField(max_length=254)),
                ("font_style", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="artcategory",
            old_name="image_filename",
            new_name="image1_filename",
        ),
    ]
