# Generated by Django 5.0.2 on 2024-09-07 20:41

import django.db.models.deletion
import kp_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kp_app", "0004_artcategorypagesettings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="category",
            field=models.ForeignKey(
                default=kp_app.models.get_default_category,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="artworks",
                to="kp_app.artcategory",
            ),
        ),
    ]
