# Generated by Django 5.0.2 on 2024-09-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kp_app", "0005_alter_artwork_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artcategorypagesettings",
            name="edu_email",
        ),
        migrations.AlterField(
            model_name="artcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
